### PR TITLE
feat(auth): match dereferenced name with spec name

### PR DESCRIPTION
**Pull request by dclipp**
## Changes proposed in this pull request

- Modifies the implementation of `continueGrant` to look for a parameter named `id` instead of `continueId`

## Context

- During debugging it was noticed that the parameter value of the `continueGrant` method was not being found
- At runtime, the property name is `id` (which matches the spec) but the function was expecting it to be named `continueId`

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [ ] Make sure that all checks pass

### CODE REVIEW

**Comment by njlie** [comment]
@dclipp Can you also include all the other methods on https://github.com/interledger/open-payments/blob/8cb2c997160a87d9ccf9307c25b1d29cb55bc0b7/auth-server-open-api-spec.yaml#L306, I think those are also destructuring by `managementId` when it should be looking for `id`.

**Comment by sabineschaller** [comment]
Three of the auth tests are failing at the moment.

**Comment by dclipp** [comment]
> @dclipp Can you also include all the other methods on https://github.com/interledger/open-payments/blob/8cb2c997160a87d9ccf9307c25b1d29cb55bc0b7/auth-server-open-api-spec.yaml#L306, I think those are also destructuring by `managementId` when it should be looking for `id`.

Fixed (as needed) and verified:

`grant` routes:
- [X] continueGrant
- [X] startInteraction
- [X] finishInteraction
- [X] denyInteraction

`access token` routes:
- [X] rotateToken
- [X] revokeToken
- [X] introspectToken

**Comment by dclipp** [comment]
> Three of the auth tests are failing at the moment.

Pushed fixes with latest commit

**Review by sabineschaller — APPROVED** [review]

**Pull request merged**
