### PR TITLE
feat: deprecate event liquidity

### PR DESCRIPTION
**Pull request by BlairCurrey**
## Changes proposed in this pull request

- moves `toLocale()` date conversions in `frontend` from server to client https://github.com/interledger/rafiki/pull/2318/commits/c8952eaee6f18a0498534af3ffeb0127030bb7ad
- fixes display amount for depositing outgoing payment liquidity in admin ui https://github.com/interledger/rafiki/pull/2318/commits/51bb314aa27b5d366594d814c5364829acd22177
- All the other changes were reviewed in the PR's for the subtasks here https://github.com/interledger/rafiki/issues/1697

Main changes:
- `depositEventLiquidity` and `withdrawEventLiquidity` resolvers have been marked as deprecated and added new `withdrawOutgoingPaymentLiquidity`, `withdrawIncomingPaymentLiquidity`, and `depositOutgoingPaymentLiquidity` resolvers that should be used instead
- liquidity fields were added to incoming/outgoing payments and wallet addresses
- Breaking changes: 
  - Renamed `addAssetLiquidity` resolver to `depositAssetLiquidity`
  - Renamed `addPeerLiquidity` resolver to `depositPeerLiquidity`
  - Renamed `addedLiquidity` field to `liquidityToDeposit` on graphql `CreateOrUpdatePeerByUrlInput`

## Context

fixes https://github.com/interledger/rafiki/issues/1697

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [ ] Make sure that all checks pass
- [ ] Postman collection updated

### CODE REVIEW

**Comment by mkurapov** [comment]
@BlairCurrey maybe we can also make the dates in the `General Information` section of the admin UI be local as well. Otherwise, UI side of things looks good

**Comment by BlairCurrey** [comment]
> @BlairCurrey maybe we can also make the dates in the `General Information` section of the admin UI be local as well. Otherwise, UI side of things looks good

yeah that makes sense. updated all of those and one in the asset fee history page.

**Comment by mkurapov** [comment]
@BlairCurrey 
Something I noticed: if we create an outgoing payment for more than what a user has on their account (and the status of the payment is FUNDING), if we click "Deposit" payment, we should display the DebitAmount we need to cover the payment instead of $0:
Screenshot 2024-01-09 at 17 15 29

**Review by mkurapov — APPROVED** [review]
🚀

**Pull request merged**
