### PR TITLE
fix: WebhookEvent models to match OpenAPI specification

### LINKED ISSUE #1715: Make webhook event payload match OpenAPI spec
## Context

The `outgoing_payment.completed` event is published with payload as `{ id, type, data: { payment: { ... }}}`, even though in the OpenAPI webhook spec, the event should be published as `{ id, type, data: { ... }}` (without the `payment` key).

We should match the code to return the data matching the OpenAPI spec. We should also confirm whether there are other webhook events that do the same incorrect behaviour.

## Todos
- [ ] Update webhook event payload to match OpenAPI webhook spec

### PR DESCRIPTION
**Pull request by daniel-shuy**
## Changes proposed in this pull request

- Fix `IncomingPaymentEvent` and `PaymentEvent` to match `incomingPaymentEvent` schema in OpenAPI specification (https://github.com/daniel-shuy/rafiki/blob/1a0468d52b743f46d756ace804b723657bb5b6ee/packages/backend/src/openapi/webhooks.yaml#L113)
- Fix `PaymentEvent` to match `outgoingPaymentEvent` schema in OpenAPI specification (804b723657bb5b6ee/packages/backend/src/openapi/webhooks.yaml#L164)

## Context

fixes #1715

## Checklist

- [x] Related issues linked using `fixes #number`
- [x] Tests added/updated
- [ ] Documentation added
- [x] Make sure that all checks pass
- [ ] Postman collection updated

### CODE REVIEW

**Comment by daniel-shuy** [comment]
Seems like the tests are flaky, the tests for the `auth` module previously failed even though they passed when I ran them locally

**Review by sabineschaller — COMMENTED** [review]
Thank you for your contribution. Since the mock account servicing entity (./localenv/mock-account-servicing-entity) consumes these webhook events, it needs to be updated as well.

**Comment by daniel-shuy** [comment]
@sabineschaller done, thanks!

**Review by sabineschaller — APPROVED** [review]
Thank you! That looks good now 🙂

**Comment by devcer** [comment]
Thank you for Contributing to Interledger during Hacktoberfest. If you have any accepted PRs, You can claim your Swag [here](https://community.interledger.org/devcer/hacktoberfest-swag-redemption-claim-your-cool-gear-2152). Last date to fill up the form is December 10th, 2023.  @daniel-shuy

**Pull request merged**
