### PR TITLE
chore: remove lint-staged commit hook ¯\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by traviscrist**
## Changes proposed in this pull request

- Remove lint-staged which prettier and eslint checks from the commit hook
- Adds new `checks` script which runs them manually `pnpm checks`
- Keeps the commit message hook

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [ ] Make sure that all checks pass

### CODE REVIEW

**Comment by cairin** [comment]
Why not just run the formatting and linting rather than just a check? There doesn't seem to be any speed advantages.

**Comment by traviscrist** [comment]
> Why not just run the formatting and linting rather than just a check? There doesn't seem to be any speed advantages.

The script is called checks, I think if we want to do formatting then we should just expand what `format` does and bring in eslint to the format script. @cairin thoughts on adding that?

**Comment by cairin** [comment]
I wouldn't put the linting in the formatting step. 

I asked because I wouldn't want to run this and then have to run formatting again afterwards if it fails. I would just want to format. It's not useful to check formatting on your local machine when you can just format - especially if it takes the same time to format and to check formatting. Same with linting, if eslint can fix some minor things and not error, why not just let it do that?

**Comment by traviscrist** [comment]
> I wouldn't put the linting in the formatting step.
> 
> I asked because I wouldn't want to run this and then have to run formatting again afterwards if it fails. I would just want to format. It's not useful to check formatting on your local machine when you can just format - especially if it takes the same time to format and to check formatting. Same with linting, if eslint can fix some minor things and not error, why not just let it do that?

I think I found a good balance. Take a look at the updated scripts. It makes `format` do all formatting and provides a `checks` which does the lint and formatting checks. Leaves it up to the developer which they want to use.

**Review by matdehaast — APPROVED** [review]

**Review by cairin — APPROVED** [review]

**Pull request merged**
