### PR TITLE
chore(interledger): refactor accounts service

### LINKED ISSUE #121: Refactor accounts service
To make the [accounts service](https://github.com/interledger/rafiki/blob/main/packages/interledger/src/accounts/service.ts) (and its [tests](https://github.com/interledger/rafiki/blob/main/packages/interledger/src/accounts/service.test.ts)) easier to manage, it could be broken into multiple services similar to the different categories of resolvers:
https://github.com/interledger/rafiki/tree/main/packages/interledger/src/admin-api/resolvers

Expose tigerbeetle balances to services other than just the account service, allowing things like outgoing payments to have a balance without creating a (sub)account

### PR DESCRIPTION
**Pull request by wilsonianb**
## Changes proposed in this pull request

before:
[](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggVERcbiAgICBHKGFkbWluLWFwaSkgJiBDKGNvbm5lY3RvcikgLS0-IEEoQWNjb3VudFNlcnZpY2UpXG4gICAgQSAtLT4gVFsoVGlnZXJCZWV0bGUpXSAmIEFjdFsoQWNjb3VudHMpXSAmIEFzc1soQXNzZXQpXSAmIFRva2VuWyhUb2tlbnMpXSIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)

after:
[](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggVERcbiAgICBDb25uZWN0b3IoY29ubmVjdG9yKVxuICAgIEFjY291bnQoQWNjb3VudFNlcnZpY2UpXG4gICAgQXNzZXQoQXNzZXRTZXJ2aWNlKVxuICAgIEJhbGFuY2UoQmFsYW5jZVNlcnZpY2UpXG4gICAgRGVwb3NpdChEZXBvc2l0U2VydmljZSlcbiAgICBXaXRoZHJhdyhXaXRoZHJhd2FsU2VydmljZSlcbiAgICBDcmVkaXQoQ3JlZGl0U2VydmljZSlcbiAgICBUcmFuc2ZlcihUcmFuc2ZlclNlcnZpY2UpXG4gICAgVG9rZW4oVG9rZW5TZXJ2aWNlKVxuICAgIEFkbWluIC0tPiBBY2NvdW50ICYgQ3JlZGl0ICYgRGVwb3NpdCAmIFdpdGhkcmF3XG4gICAgQ29ubmVjdG9yIC0tPiBUcmFuc2ZlciAmIEFjY291bnRcbiAgICBBY2NvdW50IC0tPiBBY2NvdW50REJbKEFjY291bnRzKV0gJiBUb2tlbiAmIEJhbGFuY2UgJiBBc3NldFxuICAgIENyZWRpdCAtLT4gQWNjb3VudCAmIEJhbGFuY2VcbiAgICBEZXBvc2l0IC0tPiBBY2NvdW50ICYgQmFsYW5jZSAmIEFzc2V0XG4gICAgVHJhbnNmZXIgLS0-IEJhbGFuY2UgJiBBY2NvdW50XG4gICAgV2l0aGRyYXcgLS0-IEFjY291bnQgJiBBc3NldCAmIEJhbGFuY2VcbiAgICBCYWxhbmNlIC0tPiBUQlsoVGlnZXJCZWV0bGUpXVxuICAgIEFzc2V0IC0tPiBCYWxhbmNlICYgQXNzZXREQlsoQXNzZXRzKV1cbiAgICBUb2tlbiAtLT4gVG9rZW5EQihUb2tlbnMgREIpIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)

## Context

fixes #121 

## Checklist

- [x] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [x] Make sure that all checks pass

### CODE REVIEW

**Comment by wilsonianb** [comment]
:thinking: Can the credit, deposit, and withdrawal services be moved to the backend?
Then the admin-api would just expose the account, balance, and asset services.

**Comment by wilsonianb** [comment]
Now I'm thinking we can allow things to actually deal with tigerbeetle balance ids (instead of only account ids):
- save an accounts table lookup for the balance ids during connector transfers
- for outgoing payments, create two balances (or even one?) instead of a (sub)account with three balances
- potentially have the backend similarly manage balances for invoices, mandates, etc

[](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggVERcbiAgICBzdWJncmFwaCBiYWNrZW5kXG4gICAgRGVwb3NpdChEZXBvc2l0U2VydmljZSlcbiAgICBXaXRoZHJhdyhXaXRoZHJhd2FsU2VydmljZSlcbiAgICBDcmVkaXQoQ3JlZGl0U2VydmljZSlcbiAgICBlbmRcbiAgICBzdWJncmFwaCBpbnRlcmxlZGdlclxuICAgIENvbm5lY3Rvcihjb25uZWN0b3IpXG4gICAgQWRtaW4oYWRtaW4tYXBpKVxuICAgIEFjY291bnQoQWNjb3VudFNlcnZpY2UpXG4gICAgQXNzZXQoQXNzZXRTZXJ2aWNlKVxuICAgIEJhbGFuY2UoQmFsYW5jZVNlcnZpY2UpXG4gICAgVHJhbnNmZXIoVHJhbnNmZXJTZXJ2aWNlKVxuICAgIFRva2VuKFRva2VuU2VydmljZSlcbiAgICBBY2NvdW50REJbKEFjY291bnRzKV1cbiAgICBUQlsoVGlnZXJCZWV0bGUpXVxuICAgIEFzc2V0REJbKEFzc2V0cyldXG4gICAgVG9rZW5EQlsoVG9rZW5zKV1cbiAgICBlbmRcbiAgICBDb25uZWN0b3IgLS0-IFRyYW5zZmVyICYgQWNjb3VudFxuICAgIENyZWRpdCAmIERlcG9zaXQgJiBXaXRoZHJhdyAtLT4gQWRtaW5cbiAgICBBZG1pbiAtLT4gVHJhbnNmZXIgJiBBY2NvdW50ICYgQXNzZXQgJiBCYWxhbmNlXG4gICAgQWNjb3VudCAtLT4gQWNjb3VudERCICYgVG9rZW4gJiBCYWxhbmNlICYgQXNzZXRcbiAgICBUcmFuc2ZlciAtLT4gVEJcbiAgICBCYWxhbmNlIC0tPiBUQlxuICAgIEFzc2V0IC0tPiBBc3NldERCQmFsYW5jZVxuICAgIFRva2VuIC0tPiBUb2tlbkRCIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)

**Comment by sentientwaffle** [comment]
So the various (tigerbeetle) balance ids would be stored in the backend's accounts table?

---
> for outgoing payments, create two balances (or even one?) instead of a (sub)account with three balances

You mean that we wouldn't need the postgres subaccount? Since afaik we still need one in tigerbeetle.

**Comment by wilsonianb** [comment]
>So the various (tigerbeetle) balance ids would be stored in the backend's accounts table?

I think the main account balance id would stay in `interledger` `AccountService`'s accounts table, but any others could be in the backend's accounts table, whether it's the current `creditExtendedBalanceId` and `lentBalanceId` or something(s) like `outgoingPaymentsBalanceId`.

The outgoing payments table would store the balance id(s) of each payment, and the invoices and mandates tables could potentially do the same.

>You mean that we wouldn't need the postgres subaccount? Since afaik we still need one in tigerbeetle.

Correct. I was already wondering how to avoid creating the un-used credit balance for outgoing payment sub-accounts, and this would more than solve that.

**Comment by wilsonianb** [comment]
The `interledger` package can be reduced to just what's needed by the connector:
- `getAccount`
- `getAccountByDestinationAddress`
- `getAccountByToken`
- `getAccountAddress`
- `transferFunds`

Everything else can live in the backend. No `interledger` graphql / admin api. Just `interledger` and `backend` connecting to the same tigerbeetle and postgres tables.

[](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggVERcbiAgICBzdWJncmFwaCBpbnRlcmxlZGdlclxuICAgIENvbm5lY3Rvcihjb25uZWN0b3IpXG4gICAgSWxwQWNjb3VudChBY2NvdW50U2VydmljZSlcbiAgICBJbHBUcmFuc2ZlcihUcmFuc2ZlclNlcnZpY2UpXG4gICAgZW5kXG4gICAgc3ViZ3JhcGggYmFja2VuZFxuICAgIERlcG9zaXQoRGVwb3NpdFNlcnZpY2UpXG4gICAgV2l0aGRyYXcoV2l0aGRyYXdhbFNlcnZpY2UpXG4gICAgT3V0Z29pbmdQYXltZW50KE91dGdvaW5nUGF5bWVudFNlcnZpY2UpXG4gICAgQWNjb3VudChBY2NvdW50U2VydmljZSlcbiAgICBBc3NldChBc3NldFNlcnZpY2UpXG4gICAgQmFsYW5jZShCYWxhbmNlU2VydmljZSlcbiAgICBUb2tlbihUb2tlblNlcnZpY2UpXG4gICAgZW5kXG4gICAgQWNjb3VudERCWyhBY2NvdW50cyldXG4gICAgVEJbKFRpZ2VyQmVldGxlKV1cbiAgICBBc3NldERCWyhBc3NldHMpXVxuICAgIFRva2VuREJbKFRva2VucyldXG4gICAgQ29ubmVjdG9yIC0tPiBJbHBBY2NvdW50ICYgSWxwVHJhbnNmZXJcbiAgICBJbHBBY2NvdW50IC0tPiBBY2NvdW50REIgJiBBc3NldERCICYgVG9rZW5EQlxuICAgIElscFRyYW5zZmVyIC0tPiBUQlxuICAgIE91dGdvaW5nUGF5bWVudCAtLT4gQWNjb3VudCAmIEJhbGFuY2VcbiAgICBEZXBvc2l0IC0tPiBCYWxhbmNlICYgQWNjb3VudFxuICAgIEFzc2V0IC0tPiBCYWxhbmNlICYgQXNzZXREQlxuICAgIFRva2VuIC0tPiBUb2tlbkRCXG4gICAgV2l0aGRyYXcgLS0-IEFjY291bnQgJiBCYWxhbmNlXG4gICAgQWNjb3VudCAtLT4gQWNjb3VudERCICYgVG9rZW4gJiBCYWxhbmNlXG4gICAgQmFsYW5jZSAtLT4gVEJcbiAgICAiLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)

**Comment by wilsonianb** [comment]
closing in favor of #132

**Pull request closed without merging**
