### PR TITLE
docs(2625): rafiki docs ia

### PR DESCRIPTION
**Pull request by hajjimo**
## Changes proposed in this pull request

- 

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [ ] Make sure that all checks pass
- [ ] Bruno collection updated

### CODE REVIEW

**Comment by sabineschaller** [comment]
This is not very easy to review. Is there a google doc we can look at?

**Comment by hajjimo** [comment]
I copied the outline from a working document authored by Melissa.  Hope this is easier to view:  

https://docs.google.com/document/d/1JkZS-Ih6MGdlG5oj3xSBFoAOA0_yBBEvPWZft526mKc/edit?usp=sharing

**Comment by mkurapov** [comment]
@hajjimo do we want to close this until we are ready to publish the new sections? In the meantime we can just use the google doc?

**Comment by hajjimo** [comment]
@mkurapov makes sense since the writers are working in Google Docs and we plan to create a new branch when it's time to move to markdown anyway.

**Pull request closed without merging**
