### PR TITLE
docs: updated READMEs and added Rafiki Admin docs

### LINKED ISSUE #2792: Create better docs for Admin UI and its auth
## Context

Currently we have only got docs for the Admin UI and its auth functionality on rafiki.dev under the local playground tab.

We need to also create a separate tab for it in the docs and dig deeper into how it uses Kratos and what the setup is.

Currently we https://github.com/interledger/rafiki/tree/main/packages/frontend/README.md and touch on it under the local playground docs: https://github.com/interledger/rafiki/tree/main/localenv#admin-ui

Also useful to look at is information about our approach to user invitation: https://www.ory.sh/docs/kratos/manage-identities/invite-users

## Todos
- [ ] #2774

### PR DESCRIPTION
**Pull request by JoblersTune**
## Changes proposed in this pull request

- Addition of Rafiki Admin pages to rafiki.dev.
- Updated READMEs to have better explanations of Rafiki Admin auth.

## Context

fixes #2792 

## Checklist

- [x] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [x] Documentation added
- [x] Make sure that all checks pass
- [ ] Bruno collection updated

### CODE REVIEW

**Comment by JoblersTune** [comment]
Temporary addition of Rafiki Admin and auth docs. I realise these will change when you add in the updated docs but thought this might be a good intermediary step?

Alternatively we can simply use this PR as my changes which I'm contributing to the docs update. Let me know what's best.

**Comment by JoblersTune** [comment]
I also think we should chose a term, either Admin UI, or Rafiki Admin. I think it's not ideal to use them both interchangeably throughout. 

I vote for Rafiki Admin.

**Review by brad-dow — APPROVED** [review]
I think this is a great interim step before the main docs update! 

This morning in our weekly tech writer meeting, we discussed Admin UI vs. Rafiki Admin and agreed with you on Rafiki Admin. We can then use “app”/”application” as a descriptor if needed in case it isn't clear if we are talking about the UI or the API (which the docs will be crystal clear on the distinction).

**Comment by JoblersTune** [comment]
> I think this is a great interim step before the main docs update!
> 
> This morning in our weekly tech writer meeting, we discussed Admin UI vs. Rafiki Admin and agreed with you on Rafiki Admin. We can then use “app”/”application” as a descriptor if needed in case it isn't clear if we are talking about the UI or the API (which the docs will be crystal clear on the distinction).

Or even Rafiki Admin UI when clarity is needed.

**Pull request merged**
