### PR TITLE
chore: remove version from monorepo package.json

### PR DESCRIPTION
**Pull request by sabineschaller**
## Changes proposed in this pull request

We don't want to publish the Rafiki packages on npm. Hence, the [version is optional](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#version). I propose removing it as long as all runs in docker. 

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [ ] Make sure that all checks pass
- [ ] Bruno collection updated

### CODE REVIEW

**Comment by sabineschaller** [comment]
We have a problem in that the admin UI displays the version and gets it from the package.json. Any ideas how else to get it? 

Or should a release PR template just check that the version was increased?

**Comment by mkurapov** [comment]
@sabineschaller 
Hmm, need to think this through, my first thought was something like pulling the git tag into and ENV variable that the admin UI could use?

**Review by mkurapov — DISMISSED** [review]

**Review by mkurapov — COMMENTED** [review]
oops, rushed it, since we need to remove it from the UI stil

**Comment by JoblersTune** [comment]
I have removed the version from the home page now.

**Review by mkurapov — APPROVED** [review]

**Pull request merged**
