### PR TITLE
fix!: typo in KRATOS_CONTAINER_PULIC_URL

### PR DESCRIPTION
**Pull request by JoblersTune**
## Changes proposed in this pull request

- fixed typo in KRATOS_CONTAINER_PULIC_URL

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [ ] Documentation added
- [ ] Make sure that all checks pass
- [ ] Bruno collection updated

### CODE REVIEW

**Comment by JoblersTune** [comment]
Seems we also need to add info about Kratos config in cases when people are using sub domains. Will address this once we are confident we have the full answer.

**Comment by JoblersTune** [comment]
Let's just fix the typo first. I'm making a separate issue to add comments about setting up Kratos on a subdomain. 

@tadejgolobic you needed the env vars for the helm charts -> do you need to fix the typo there as well?

**Comment by tadejgolobic** [comment]
> Let's just fix the typo first. I'm making a separate issue to add comments about setting up Kratos on a subdomain.
> 
> @tadejgolobic you needed the env vars for the helm charts -> do you need to fix the typo there as well?

Yes I do. I will fix that as soon you merge this PR.

**Review by mkurapov — APPROVED** [review]

**Comment by JoblersTune** [comment]
@tadejgolobic this has been merged now

**Pull request merged**
